services:
  nginx:
    image: nginx:alpine
    container_name: master-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - /etc/ssl/certs/cloudflare.pem:/etc/ssl/certs/cloudflare.pem:ro
      - /etc/ssl/private/cloudflare.key:/etc/ssl/private/cloudflare.key:ro
    networks:
      - dlrs-net
    depends_on:
      - frontend
      - blog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  blog:
    container_name: blog
    restart: always
    build: ./apps/blog
    networks:
      - dlrs-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    restart: always
    build:
      context: ./apps/fp-app/fingerprint-client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    networks:
      - dlrs-net
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    restart: always
    build: ./apps/fp-app/fingerprint-server
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - dlrs-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data-prod:/data/db
    env_file:
      - ./.env
    networks:
      - dlrs-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data-prod:

networks:
  dlrs-net:
    driver: bridge