services:
  nginx:
    image: nginx:alpine
    container_name: master-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro  
      - /etc/ssl/certs/cloudflare.pem:/etc/ssl/certs/cloudflare.pem:ro
      - /etc/ssl/private/cloudflare.key:/etc/ssl/private/cloudflare.key:ro
    networks:
      - dlrs-net
    depends_on:
      - frontend

  frontend:
    restart: always
    build: 
      context: ./apps/fp-app/fingerprint-client
      dockerfile: Dockerfile 
      args:
        - VITE_API_URL=/api
    networks:
      - dlrs-net
    depends_on:
      - api

  api: 
    restart: always
    build: ./apps/fp-app/fingerprint-server
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    networks: 
      - dlrs-net
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data-prod:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - dlrs-net

volumes:
  mongo-data-prod:

networks:
  dlrs-net:
    driver: bridge