baseURL = 'https://dlrs.me/'
theme = 'PaperMod'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = "English"
    title = "DLRS"
    contentDir = "content/en" # Posts go in /content/en/
    weight = 1
  
  [languages.es]
    languageName = "Español"
    title = "DLRS"
    contentDir = "content/es" # Posts go in /content/es/
    weight = 2